services:
    dlna-web:
        container_name: dlna-web
        build:
            context: .
            dockerfile: ./docker/dlna-web/Dockerfile
        # image: jkerdreux-imt/dlna-web:latest
        image: ghcr.io/jkerdreux-imt/dlna-web:latest
        restart: unless-stopped
        stop_grace_period: 1s 
        network_mode: host
        environment:
            SERVER_PATH: '/dlna: minidlna/'
