services:
    dlna-web:
        container_name: dlna-web
        build: dlna-web
        image: jkerdreux-imt/dlna-web:latest
        restart: unless-stopped
        stop_grace_period: 1s 
        network_mode: host
        environment:
            SERVER_PATH: '/data: minidlna/divx/'
